name: TICS Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"

jobs:
  TICSQServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots clean install -P enable-jacoco
      - name: Run TICSQServer
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: Jenkins
          branchdir: .
          viewerUrl: https://eboit.tiobe.com/tiobeweb/TICS/api/cfg?name=main
          ticsAuthToken: ${{ secrets.EBOIT_ANALYZER_TOKEN }}
          installTics: true
